import React from 'react';
import { Monitor, Play, RefreshCw, Save, Send, TimerReset } from 'lucide-react';
import { api } from '../services/api';
import type { ContentPlaylist, Screen, ScreenGroup } from '../types';

const defaults: Record<string, any> = {resolutionWidth:1920,resolutionHeight:1080,orientation:'LANDSCAPE',contentRotation:0,imageFit:'CONTAIN',backgroundColor:'#000000',keepScreenAwake:true,defaultSlideDurationSeconds:10,transition:'FADE',transitionDurationMs:500,playbackOrder:'PLAYLIST_ORDER',repeatPlaylist:true,fallbackPlaylistId:null,updateCheckIntervalSeconds:60,offlinePlayback:true,downloadConnection:'ANY',startOnBoot:true,scheduleTimezone:'Asia/Kolkata',excludeExpiredContent:true,deleteExpiredLocalFiles:true,localDeletionGraceHours:24};
const field='w-full border border-sky-200 rounded-md px-2.5 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-sky-100';
const label='text-xs text-slate-600 space-y-1';
const sections=[
  {title:'Display',icon:Monitor,fields:[['resolutionWidth','Canvas width','number'],['resolutionHeight','Canvas height','number'],['orientation','Orientation',['LANDSCAPE','PORTRAIT']],['contentRotation','Content rotation',[0,90,180,270]],['imageFit','Image fit',['CONTAIN','COVER','STRETCH']],['backgroundColor','Background colour','color'],['keepScreenAwake','Keep screen awake','boolean']]},
  {title:'Playback',icon:Play,fields:[['defaultSlideDurationSeconds','Default slide duration (sec)','number'],['transition','Transition',['NONE','FADE','SLIDE_LEFT','SLIDE_RIGHT','SLIDE_UP','SLIDE_DOWN','ZOOM_IN','ZOOM_OUT','FADE_ZOOM']],['transitionDurationMs','Transition duration (ms)','number'],['playbackOrder','Playback order',['PLAYLIST_ORDER','SHUFFLE']],['repeatPlaylist','Repeat playlist','boolean'],['fallbackPlaylistId','Fallback playlist','playlist']]},
  {title:'Synchronization',icon:RefreshCw,fields:[['updateCheckIntervalSeconds','Update interval (sec)','number'],['offlinePlayback','Offline playback','boolean'],['downloadConnection','Download connection',['ANY','WIFI_ONLY']],['startOnBoot','Start on device boot','boolean']]},
  {title:'Schedule & Expiry',icon:TimerReset,fields:[['scheduleTimezone','Schedule timezone','text'],['excludeExpiredContent','Exclude expired content','boolean'],['deleteExpiredLocalFiles','Delete expired local files','boolean'],['localDeletionGraceHours','Deletion grace period (hours)','number']]}
] as any[];

export function GeneralSettings(){
  const [scope,setScope]=React.useState('COMMON'),[scopeId,setScopeId]=React.useState('common');
  const [screens,setScreens]=React.useState<Screen[]>([]),[groups,setGroups]=React.useState<ScreenGroup[]>([]),[playlists,setPlaylists]=React.useState<ContentPlaylist[]>([]);
  const [overrides,setOverrides]=React.useState<Record<string,any>>({}),[effective,setEffective]=React.useState<Record<string,any>>(defaults),[sources,setSources]=React.useState<Record<string,string>>({});
  const [lastPublished,setLastPublished]=React.useState<any>(null),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false);
  React.useEffect(()=>{Promise.all([api.getScreens(),api.getScreenGroups(),api.getContentPlaylists()]).then(([s,g,p])=>{setScreens(s);setGroups(g);setPlaylists(p);});},[]);
  React.useEffect(()=>{if(scope!=='COMMON'&&!scopeId)return;api.getGeneralSettingsDraft(scope,scopeId).then(data=>{setOverrides(data.overrides||{});setEffective(data.effective?.values||{...defaults,...data.overrides});setSources(data.effective?.sources||{});setLastPublished(data.lastPublished);setMessage('');}).catch(e=>setMessage(e.message));},[scope,scopeId]);
  const changeScope=(next:string)=>{setScope(next);setScopeId(next==='COMMON'?'common':next==='GROUP'?(groups[0]?.id||''):(screens[0]?.id||''));};
  const value=(key:string)=>Object.prototype.hasOwnProperty.call(overrides,key)?overrides[key]:effective[key]??defaults[key];
  const update=(key:string,next:any)=>setOverrides(current=>({...current,[key]:next}));
  const save=async()=>{setBusy(true);try{await api.saveGeneralSettingsDraft(scope,scopeId,overrides);setMessage('Draft saved. Devices remain unchanged until Publish Settings.');}catch(e){setMessage(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}};
  const publish=async()=>{setBusy(true);try{await api.saveGeneralSettingsDraft(scope,scopeId,overrides);const result=await api.publishGeneralSettings(scope,scopeId);setMessage(`Published to ${result.targets.length} device${result.targets.length===1?'':'s'}. Waiting for exact-version acknowledgements.`);const data=await api.getGeneralSettingsDraft(scope,scopeId);setLastPublished(data.lastPublished);}catch(e){setMessage(e instanceof Error?e.message:'Publish failed');}finally{setBusy(false);}};
  const reset=async()=>{setBusy(true);try{await api.resetGeneralSettings(scope,scopeId);setOverrides({});setMessage('Overrides reset in the draft. Publish to apply inherited settings.');}catch(e){setMessage(e instanceof Error?e.message:'Reset failed');}finally{setBusy(false);}};
  return <div className="space-y-4">
    <div className="bg-white border border-sky-100 rounded-xl p-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900">General Settings</h2><p className="text-xs text-slate-500">Canvas resolution controls content layout; it does not change the TV's physical resolution.</p></div><div className="flex gap-2"><select className={field} value={scope} onChange={e=>changeScope(e.target.value)}><option value="COMMON">Common settings</option><option value="GROUP">Screen group overrides</option><option value="SCREEN">Screen overrides</option></select>{scope==='GROUP'&&<select className={field} value={scopeId} onChange={e=>setScopeId(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select>}{scope==='SCREEN'&&<select className={field} value={scopeId} onChange={e=>setScopeId(e.target.value)}>{screens.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</div></div>
    <div className="grid xl:grid-cols-2 gap-4">{sections.map(section=><section key={section.title} className="bg-white border border-sky-100 rounded-xl p-4"><h3 className="text-sm font-medium text-slate-900 flex items-center gap-2 mb-3"><section.icon className="w-4 h-4 text-sky-600"/>{section.title}</h3><div className="grid sm:grid-cols-2 gap-3">{section.fields.map(([key,title,type]:any)=><label key={key} className={label}><span className="flex justify-between">{title}{scope!=='COMMON'&&<small className="text-sky-600">{Object.prototype.hasOwnProperty.call(overrides,key)?'Override':sources[key]||'Inherited'}</small>}</span>{type==='boolean'?<select className={field} value={String(value(key))} onChange={e=>update(key,e.target.value==='true')}><option value="true">Enabled</option><option value="false">Disabled</option></select>:type==='playlist'?<select className={field} value={value(key)||''} onChange={e=>update(key,e.target.value||null)}><option value="">None</option>{playlists.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>:Array.isArray(type)?<select className={field} value={value(key)} onChange={e=>update(key,typeof type[0]==='number'?Number(e.target.value):e.target.value)}>{type.map((v:any)=><option key={v} value={v}>{String(v).replaceAll('_',' ')}</option>)}</select>:<input className={field} type={type} value={value(key)} onChange={e=>update(key,type==='number'?Number(e.target.value):e.target.value)}/>}</label>)}</div>{section.title==='Synchronization'&&<p className="text-[11px] text-amber-700 bg-amber-50 rounded p-2 mt-3">Start on boot depends on Android platform, launcher, and kiosk/device-owner permissions. Publishing cannot grant system permissions.</p>}</section>)}</div>
    <div className="bg-white border border-sky-100 rounded-xl p-4 flex flex-wrap justify-between items-center gap-3"><div className="text-xs text-slate-500">{lastPublished?`Last published v${lastPublished.version} · ${new Date(lastPublished.publishedAt).toLocaleString()}`:'Not published yet'}{message&&<span className="block text-sky-700 mt-1">{message}</span>}</div><div className="flex gap-2">{scope!=='COMMON'&&<button disabled={busy} onClick={reset} className="border border-sky-200 text-sky-700 rounded px-3 py-2 text-xs">Reset Overrides</button>}<button disabled={busy} onClick={save} className="border border-sky-200 text-sky-700 rounded px-3 py-2 text-xs inline-flex gap-1"><Save className="w-3.5 h-3.5"/>Save Draft</button><button disabled={busy} onClick={publish} className="bg-sky-600 text-white rounded px-3 py-2 text-xs inline-flex gap-1"><Send className="w-3.5 h-3.5"/>Publish Settings</button></div></div>
  </div>;
}
