import { CalendarDays, CloudDownload, Images, Monitor, PlaySquare, Send, Users } from 'lucide-react';

export function LandingPage({onLogin}:{onLogin:()=>void}) {
  const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
  return <div className="min-h-screen bg-white text-slate-950 overflow-x-hidden">
    <header className="h-16 bg-white border-b border-sky-100 sticky top-0 z-40"><div className="max-w-7xl mx-auto h-full px-5 flex items-center justify-between gap-5"><img src="/ekshitascreen-logo.png" alt="EkshitaScreen" width="240" height="64" className="h-14 w-auto object-contain"/><nav aria-label="Landing navigation" className="hidden sm:flex items-center gap-8 text-sm"><button onClick={()=>go('features')} className="focus-visible:outline-2 focus-visible:outline-sky-600">Features</button><button onClick={()=>go('how-it-works')} className="focus-visible:outline-2 focus-visible:outline-sky-600">How It Works</button><button onClick={()=>go('contact')} className="focus-visible:outline-2 focus-visible:outline-sky-600">Contact</button></nav><button onClick={onLogin} className="shrink-0 rounded-md bg-blue-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">Login</button></div></header>
    <main>
      <section className="bg-sky-50 border-b border-sky-100"><div className="max-w-7xl mx-auto px-5 py-12 md:py-16 grid lg:grid-cols-[.85fr_1.15fr] gap-12 items-center"><div><p className="text-xs font-semibold tracking-[.2em] text-blue-600">SMART DIGITAL SIGNAGE</p><h1 className="mt-4 text-5xl md:text-6xl font-bold tracking-tight leading-[1.04] text-slate-950">Your screens.<br/>Your content.<br/><span className="text-blue-600">Anywhere.</span></h1><p className="mt-5 max-w-xl text-lg text-slate-600">Manage playlists, schedule content, and publish to your Android screens from one dashboard.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={onLogin} className="rounded-md bg-blue-600 px-8 py-3.5 font-medium text-white hover:bg-blue-700">Get Started</button><button onClick={()=>go('features')} className="rounded-md border-2 border-blue-600 bg-white px-8 py-3 text-blue-600 font-medium hover:bg-sky-50">Explore Features</button></div></div><HeroVisual/></div></section>
      <section id="features" className="scroll-mt-20 max-w-7xl mx-auto px-5 py-12"><h2 className="text-center text-3xl font-semibold tracking-tight">Everything you need to manage your screens</h2><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{[[Images,'Playlists','Organize images and playback order.'],[CalendarDays,'Scheduling','Show the right content at the right time.'],[Users,'Screen Groups','Publish to multiple screens together.'],[CloudDownload,'Offline Playback','Keep downloaded content playing.']].map(([Icon,title,text]:any)=><article key={title} className="border border-sky-200 rounded-lg p-6 flex gap-4 shadow-sm"><Icon className="w-10 h-10 text-blue-600 stroke-[1.7] shrink-0"/><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-600">{text}</p></div></article>)}</div></section>
      <section id="how-it-works" className="scroll-mt-20 bg-sky-50 border-y border-sky-100"><div className="max-w-7xl mx-auto px-5 py-10 grid md:grid-cols-3 gap-8">{[[Monitor,'Connect your screen','Install our Android app and link your screen.'],[PlaySquare,'Create a playlist','Upload content and organize your media.'],[Send,'Publish and play','Send content to your screens.']].map(([Icon,title,text]:any,index)=><article key={title} className="flex items-center gap-4"><span className="w-8 h-8 rounded-full bg-blue-600 text-white text-sm flex items-center justify-center">{index+1}</span><Icon className="w-10 h-10 text-blue-600 stroke-[1.7]"/><div><h3 className="font-semibold">{title}</h3><p className="text-sm text-slate-600">{text}</p></div></article>)}</div></section>
      <section id="contact" className="scroll-mt-20 max-w-3xl mx-auto px-5 py-12 text-center"><h2 className="text-2xl font-semibold">Contact</h2><p className="mt-2 text-slate-600">Contact details can be configured by your EkshitaScreen administrator.</p></section>
    </main>
    <footer className="border-t border-sky-100"><div className="max-w-7xl mx-auto px-5 py-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-500"><div className="flex items-center gap-4"><img src="/ekshitascreen-logo.png" alt="EkshitaScreen" width="160" height="40" className="h-10 w-auto"/><span className="border-l border-slate-300 pl-4">Digital Signage Made Simple.</span></div><span>© {new Date().getFullYear()} EkshitaScreen</span></div></footer>
  </div>;
}

function HeroVisual(){return <div aria-label="Android TV signage and EkshitaScreen dashboard preview" className="relative min-h-[380px]"><div className="absolute left-0 top-3 w-[72%]"><div className="border-[10px] border-slate-800 bg-slate-900 rounded-md aspect-video p-6 flex flex-col justify-center text-white"><p className="text-4xl font-semibold">FRESH<br/>FLAVOURS</p><span className="mt-8 text-xs tracking-[.25em]">GOOD FOOD<br/>BRIGHTER DAYS</span></div><div className="mx-auto h-4 w-32 bg-slate-700"/><div className="mx-auto h-2 w-48 bg-slate-800 rounded-full"/></div><div className="absolute right-0 bottom-0 w-[62%] rounded-lg border-8 border-slate-800 bg-white shadow-xl"><div className="h-8 border-b border-sky-100 px-2 flex items-center"><img src="/ekshitascreen-logo.png" alt="" className="h-7 w-auto"/></div><div className="grid grid-cols-[74px_1fr] min-h-48"><div className="bg-sky-50 border-r border-sky-100 p-2 space-y-2 text-[8px] text-slate-500"><b className="text-blue-600">Dashboard</b><span className="block">Playlists</span><span className="block">Screens</span><span className="block">Scheduling</span><span className="block">Settings</span></div><div className="p-3"><b className="text-xs">Screens</b>{['Reception Display','Restaurant Screen','Outdoor Display'].map(name=><div key={name} className="mt-3 flex items-center gap-2 text-[9px]"><Monitor className="w-3 h-3 text-blue-600"/><span className="flex-1">{name}</span><span className="rounded bg-emerald-100 px-1.5 py-0.5 text-emerald-700">Online</span></div>)}</div></div></div></div>}
